import { Recipe } from "../types";

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Спагеті Карбонара",
    description: "Класичний італійський рецепт з яйцями, сиром та беконом",
    image:
      "https://myastoriya.com.ua/upload/iblock/153/m7tqlwgeqe40p1v6v1zjpb59ztce5843.jpg",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "medium",
    cuisine: "Італійська",
    tags: ["паста", "яйця", "бекон", "сир"],
    ingredients: [
      {
        id: "1",
        name: "Спагеті",
        amount: 400,
        unit: "г",
        notes: "тверді сорти пшениці",
      },
      {
        id: "2",
        name: "Яйця",
        amount: 4,
        unit: "шт",
      },
      {
        id: "3",
        name: "Пармезан",
        amount: 100,
        unit: "г",
        notes: "тертий",
      },
      {
        id: "4",
        name: "Гуанчале",
        amount: 150,
        unit: "г",
        notes: "або панчетта",
      },
      {
        id: "5",
        name: "Чорний перець",
        amount: 1,
        unit: "ч.л",
        notes: "свіжо мелений",
      },
      {
        id: "6",
        name: "Сіль",
        amount: 1,
        unit: "ч.л",
      },
    ],
    instructions: [
      "Варіть спагеті в підсоленій воді до стану al dente",
      "Підсмажте нарізаний гуанчале до хрусткості",
      "У мисці збийте яйця з тертим пармезаном та перцем",
      "Змішайте гарячі спагеті з яєчною сумішшю та гуанчале",
      "Подавайте з додатковим тертим пармезаном та перцем",
    ],
    nutrition: {
      calories: 450,
      protein: 18,
      carbs: 65,
      fat: 15,
      fiber: 3,
      sugar: 2,
    },
    author: {
      name: "Chef Mario",
      avatar:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    },
    rating: 4.8,
    reviews: 124,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Салат Цезар",
    description: "Свіжий салат з хрусткими грінками та соусом Цезар",
    image:
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 10,
    servings: 2,
    difficulty: "easy",
    cuisine: "Американська",
    tags: ["салат", "курятина", "грінки", "сир"],
    ingredients: [
      {
        id: "1",
        name: "Ромен салат",
        amount: 1,
        unit: "шт",
        notes: "великий кочан",
      },
      {
        id: "2",
        name: "Куряче філе",
        amount: 200,
        unit: "г",
      },
      {
        id: "3",
        name: "Хліб",
        amount: 100,
        unit: "г",
        notes: "для грінок",
      },
      {
        id: "4",
        name: "Пармезан",
        amount: 50,
        unit: "г",
        notes: "тертий",
      },
      {
        id: "5",
        name: "Оливкова олія",
        amount: 60,
        unit: "мл",
      },
      {
        id: "6",
        name: "Лимонний сік",
        amount: 30,
        unit: "мл",
      },
      {
        id: "7",
        name: "Часник",
        amount: 2,
        unit: "зубки",
      },
      {
        id: "8",
        name: "Анчоуси",
        amount: 4,
        unit: "шт",
      },
    ],
    instructions: [
      "Підсмажте куряче філе до готовності та наріжте",
      "Приготуйте грінки з хліба та часнику",
      "Змішайте оливкову олію, лимонний сік, часник та анчоуси для соусу",
      "Наріжте салат та змішайте з соусом",
      "Додайте курятину, грінки та тертий пармезан",
    ],
    nutrition: {
      calories: 320,
      protein: 25,
      carbs: 15,
      fat: 20,
      fiber: 4,
      sugar: 1,
    },
    author: {
      name: "Chef Julia",
      avatar:
        "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    },
    rating: 4.6,
    reviews: 89,
    createdAt: "2024-01-16T12:00:00Z",
    updatedAt: "2024-01-16T12:00:00Z",
  },
  {
    id: "3",
    title: "Тірамісу",
    description: "Італійський десерт з кавою та маскарпоне",
    image:
      "https://ulichnayaeda.com.ua/wp-content/uploads/2024/09/maxresdefault.jpg",
    prepTime: 30,
    cookTime: 0,
    servings: 6,
    difficulty: "medium",
    cuisine: "Італійська",
    tags: ["десерт", "кава", "маскарпоне", "яйця"],
    ingredients: [
      {
        id: "1",
        name: "Яйця",
        amount: 6,
        unit: "шт",
        notes: "розділити білки та жовтки",
      },
      {
        id: "2",
        name: "Цукор",
        amount: 150,
        unit: "г",
      },
      {
        id: "3",
        name: "Маскарпоне",
        amount: 500,
        unit: "г",
      },
      {
        id: "4",
        name: "Кава",
        amount: 300,
        unit: "мл",
        notes: "еспресо, охолоджена",
      },
      {
        id: "5",
        name: "Савоярді",
        amount: 200,
        unit: "г",
      },
      {
        id: "6",
        name: "Какао порошок",
        amount: 30,
        unit: "г",
      },
    ],
    instructions: [
      "Збийте жовтки з цукром до світлого кольору",
      "Додайте маскарпоне та змішайте до однорідності",
      "Окремо збийте білки до піків та обережно змішайте з сумішшю",
      "Змочіть савоярді в каві та викладіть шар на дно форми",
      "Покладіть шар крему, повторіть шари",
      "Присипте какао та поставте в холодильник на 4 години",
    ],
    nutrition: {
      calories: 380,
      protein: 8,
      carbs: 35,
      fat: 22,
      fiber: 1,
      sugar: 1,
    },
    author: {
      name: "Chef Antonio",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    },
    rating: 4.9,
    reviews: 156,
    createdAt: "2024-01-17T14:00:00Z",
    updatedAt: "2024-01-17T14:00:00Z",
  },
  {
    id: "4",
    title: "Пад Тай",
    description: "Тайська страва з рисовою локшиною та морепродуктами",
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&h=600&fit=crop",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: "hard",
    cuisine: "Тайська",
    tags: ["локшина", "морепродукти", "соєвий соус", "імбир"],
    ingredients: [
      {
        id: "1",
        name: "Рисова локшина",
        amount: 200,
        unit: "г",
      },
      {
        id: "2",
        name: "Креветки",
        amount: 300,
        unit: "г",
        notes: "очищені",
      },
      {
        id: "3",
        name: "Яйця",
        amount: 2,
        unit: "шт",
      },
      {
        id: "4",
        name: "Тофу",
        amount: 150,
        unit: "г",
        notes: "нарізаний",
      },
      {
        id: "5",
        name: "Ростки квасолі",
        amount: 100,
        unit: "г",
      },
      {
        id: "6",
        name: "Часник",
        amount: 4,
        unit: "зубки",
      },
      {
        id: "7",
        name: "Імбир",
        amount: 20,
        unit: "г",
      },
      {
        id: "8",
        name: "Соєвий соус",
        amount: 60,
        unit: "мл",
      },
      {
        id: "9",
        name: "Рибний соус",
        amount: 30,
        unit: "мл",
      },
      {
        id: "10",
        name: "Лайм",
        amount: 2,
        unit: "шт",
      },
    ],
    instructions: [
      "Замочіть локшину в теплій воді на 30 хвилин",
      "Розігрійте вок на високому вогні",
      "Підсмажте яйця та винесіть",
      "Підсмажте часник та імбир, додайте креветки",
      "Додайте локшину, соуси та овочі",
      "Змішайте з яйцями та подавайте з лаймом",
    ],
    nutrition: {
      calories: 420,
      protein: 28,
      carbs: 45,
      fat: 18,
      fiber: 6,
      sugar: 1,
    },
    author: {
      name: "Chef Somchai",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    },
    rating: 4.7,
    reviews: 78,
    createdAt: "2024-01-18T16:00:00Z",
    updatedAt: "2024-01-18T16:00:00Z",
  },
  {
    id: "5",
    title: "Борщ",
    description: "Традиційна українська страва з буряком та м'ясом",
    image:
      "https://images.unian.net/photos/2022_09/thumb_files/1000_545_1662892107-3846.jpg",
    prepTime: 45,
    cookTime: 120,
    servings: 8,
    difficulty: "medium",
    cuisine: "Українська",
    tags: ["суп", "буряк", "м'ясо", "овочі"],
    ingredients: [
      {
        id: "1",
        name: "Говядина",
        amount: 800,
        unit: "г",
        notes: "на кістці",
      },
      {
        id: "2",
        name: "Буряк",
        amount: 400,
        unit: "г",
      },
      {
        id: "3",
        name: "Капуста",
        amount: 300,
        unit: "г",
        notes: "білокачанна",
      },
      {
        id: "4",
        name: "Картопля",
        amount: 400,
        unit: "г",
      },
      {
        id: "5",
        name: "Морква",
        amount: 200,
        unit: "г",
      },
      {
        id: "6",
        name: "Цибуля",
        amount: 150,
        unit: "г",
      },
      {
        id: "7",
        name: "Часник",
        amount: 6,
        unit: "зубки",
      },
      {
        id: "8",
        name: "Лавровий лист",
        amount: 3,
        unit: "шт",
      },
      {
        id: "9",
        name: "Сіль",
        amount: 2,
        unit: "ч.л",
      },
      {
        id: "10",
        name: "Перець",
        amount: 1,
        unit: "ч.л",
      },
    ],
    instructions: [
      "Варити м'ясо в підсоленій воді 1.5 години",
      "Додати нарізані овочі та варити ще 30 хвилин",
      "Додати капусту та картоплю",
      "Варити до готовності овочів",
      "Додати часник та спеції за 5 хвилин до кінця",
      "Подавати зі сметаною та хлібом",
    ],
    nutrition: {
      calories: 280,
      protein: 22,
      carbs: 25,
      fat: 12,
      fiber: 6,
      sugar: 1,
    },
    author: {
      name: "Chef Olena",
      avatar:
        "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    },
    rating: 4.9,
    reviews: 203,
    createdAt: "2024-01-19T18:00:00Z",
    updatedAt: "2024-01-19T18:00:00Z",
  },
];

export const mockCuisines = [
  "Італійська",
  "Американська",
  "Тайська",
  "Українська",
  "Французька",
  "Японська",
  "Індійська",
  "Мексиканська",
];

export const mockTags = [
  "паста",
  "салат",
  "десерт",
  "локшина",
  "суп",
  "м'ясо",
  "морепродукти",
  "овочі",
  "сир",
  "яйця",
  "кава",
  "соєвий соус",
];
